In [1]:
print('Hello World')

Hello World

# Criar um data frame (trazer os dados para a memória do python)

In [4]:
import pandas as pd

df = pd.read_csv('dados.csv')
display(df)

       marca      modelo     cor   ano   valor
0         VW       Fusca  Branco  1985   25000
1  Chevrolet       Opala   Preto  1979   52500
2       Fiat       Marea   Preto  2001   15680
3         VW  Variant II  Branco  1971    5800
4  Chevrolet    Chevette    Bege  1985   10000
5        BMW        320i   Prata  2017   80620
6      Honda       Civic   Prata  2023  140000

In [14]:
#head - imprime apenas uma amostra dos dados
print(df.head(2))

print('\n')

#info - apresenta um resumo do "dataset"
print(df.info())

print('\n')

#describe - soma a média. min, max... dos registros da tabela
print(df.describe())

print('\n')

# shape - mostra total de registros e colunas
print(df.shape)

print('\n')

#columns - identifica o titulo de cada coluna...
print(df.columns)

       marca modelo     cor   ano  valor
0         VW  Fusca  Branco  1985  25000
1  Chevrolet  Opala   Preto  1979  52500


<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   marca   7 non-null      str
 1   modelo  7 non-null      str
 2   cor     7 non-null      str
 3   ano     7 non-null      int64
 4   valor   7 non-null      int64
dtypes: int64(2), str(3)
memory usage: 412.0 bytes
None


               ano          valor
count     7.000000       7.000000
mean   1994.428571   47085.714286
std      19.721876   48889.135418
min    1971.000000    5800.000000
25%    1982.000000   12840.000000
50%    1985.000000   25000.000000
75%    2009.000000   66560.000000
max    2023.000000  140000.000000


(7, 5)


Index(['marca', 'modelo', 'cor', 'ano', 'valor'], dtype='str')

In [20]:
marca = df['marca']
print(marca)

print('\n')

#consulta direto no print
print(df['modelo'])

print('\n')

#consultar mais que uma coluna
marca_modelo = df[['marca','modelo','cor']]
display(marca_modelo)

0           VW
1    Chevrolet
2         Fiat
3           VW
4    Chevrolet
5          BMW
6        Honda
Name: marca, dtype: str


0         Fusca
1         Opala
2         Marea
3    Variant II
4      Chevette
5          320i
6         Civic
Name: modelo, dtype: str

       marca      modelo     cor
0         VW       Fusca  Branco
1  Chevrolet       Opala   Preto
2       Fiat       Marea   Preto
3         VW  Variant II  Branco
4  Chevrolet    Chevette    Bege
5        BMW        320i   Prata
6      Honda       Civic   Prata

# Criar filtros

In [32]:
# quero saber quantos carros não pagam mais ipva no meu estoque 
nipva = df[df['ano'] < 2006]
display(nipva)

print('\n')

# apresenta os que custam mais que 20 mil reais
ipva = df[df['valor'] > 20000]
display(ipva)

print('\n')

# apresente apenas os carros da chevrolet
CVT = df[df['marca'] == 'Chevrolet']
display(CVT)

       marca      modelo     cor   ano  valor
0         VW       Fusca  Branco  1985  25000
1  Chevrolet       Opala   Preto  1979  52500
2       Fiat       Marea   Preto  2001  15680
3         VW  Variant II  Branco  1971   5800
4  Chevrolet    Chevette    Bege  1985  10000

       marca modelo     cor   ano   valor
0         VW  Fusca  Branco  1985   25000
1  Chevrolet  Opala   Preto  1979   52500
5        BMW   320i   Prata  2017   80620
6      Honda  Civic   Prata  2023  140000

       marca    modelo    cor   ano  valor
1  Chevrolet     Opala  Preto  1979  52500
4  Chevrolet  Chevette   Bege  1985  10000